services:
  # MySQL 服务
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sgcc_news
    volumes:
      - mysql_data:/var/lib/mysql  # 持久化数据库数据
    ports:
      - "3307:3306"
    restart: always

  # 爬虫服务
  crawler:
    build: .
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql  # 与 MySQL 服务名一致（Docker 内部网络自动解析）
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: sgcc_news
    volumes:
      - ./articles:/app/articles       # 挂载本地目录，持久化文章
      - ./visualizations:/app/visualizations  # 挂载本地目录，持久化图表
    command: python src/crawler.py --mode full  # 可改为 incremental 增量模式
    restart: on-failure

volumes:
  mysql_data:  # MySQL 数据卷