version: '3.8'

services:
  # MySQL 数据库服务
  mysql:
    image: mysql:8.0  # 使用稳定的MySQL 8.0版本
    environment:
      MYSQL_ROOT_PASSWORD: '123456'  # 与src/config.py默认密码一致
      MYSQL_DATABASE: 'sgcc_news'     # 与项目数据库名一致
      MYSQL_CHARSET: 'utf8mb4'
    volumes:
      - mysql_data:/var/lib/mysql  # 持久化数据库数据
    ports:
      - '3307:3306'  # 映射端口方便外部工具连接（如Navicat）
    restart: always  # 容器意外停止后自动重启

  # 爬虫服务
  crawler:
    build: .  # 基于当前目录的Dockerfile构建镜像
    depends_on:
      - mysql  # 依赖MySQL服务启动完成
    environment:
      # 通过环境变量覆盖src/config.py中的MySQL配置（无需修改源代码）
      MYSQL_HOST: 'mysql'       # MySQL服务名（docker-compose内部DNS解析）
      MYSQL_USER: 'root'        # 与config.py默认一致
      MYSQL_PASSWORD: '123456'  # 与config.py默认一致
      MYSQL_DATABASE: 'sgcc_news'  # 与config.py默认一致
    volumes:
      - ./articles:/app/articles      # 挂载文章输出目录到宿主机
      - ./visualization:/app/visualization  # 挂载可视化图表目录到宿主机
    command: python src/crawler.py --mode full  # 默认全量爬取（可修改为incremental或添加--schedule）
    restart: unless-stopped  # 除非手动停止，否则自动重启

volumes:
  # 持久化MySQL数据卷（避免容器删除后数据丢失）
  mysql_data: